
title: Ohjelmistotuotanto
email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ''
url: 'https://ohjelmistotuotanto-hy.github.io'
github_username: mluukkai
repo_url: 'https://github.com/ohjelmistotuotanto-hy/ohjelmistotuotanto-hy.github.io'
repo_branch: 'master'
stats_url: 'https://study.cs.helsinki.fi/stats/courses/ohtu2024'

python_exercise_repo_url: 'https://github.com/ohjelmistotuotanto-hy/tehtavat'
java_exercise_repo_url: 'https://github.com/ohjelmistotuotanto-hy/syksy2021-java'

norppa: https://norppa.helsinki.fi/targets/83083419/feedback

moniv-dl:
  - 'FAIL'
  - 'sunnuntai 10.11. klo 23:59:00'
  - 'sunnuntai 10.11. klo 23:59:00'
  - 'sunnuntai 17.11. klo 23:59:00'
  - 'sunnuntai 24.11. klo 23:59:00'
  - 'sunnuntai 1.12. klo 23:59:00'
  - 'ei teht채vi채'
  - 'ei teht채vi채'

lask-dl:
  - 'FAIL'
  - 'maanantai 4.11. klo 23:59'
  - 'maanantai 11.11. klo 23:59'
  - 'maanantai 18.11. klo 23:59'
  - 'maanantai 25.11. klo 23:59'
  - 'maanantai 2.12. klo 23:59'
  - 'maanantai 9.12. klo 23:59'
  - 'keskiviikko 20.12. klo 23:59'

luennot:
  - 'FAIL'
  - 'maanantai 28.10. tallenne'
  - 'tiistai 5.11. klo 12-14 B123'
  - 'torstaina 7.11. klo 12-14 CK112'
  - 'perjantaina 8.11. klo 12-14 B123'
  - 'maanantai 11.11. klo 12-14 B123'
  - 'tiistai 12.11. klo 12-14 B123'
  - 'maanantai 18.11. klo 12-14 B123'
  - 'tiistai 19.11. klo 12-14 B123'
  - 'maanantai 25.11. klo 12-14 B123'
  - 'tiistai 26.11. klo 12-14 B123'
  - 'maanantai 2.12. klo 12-14 B123'
  - 'tiistai 3.12. klo 12-14 B123'
  - 'maanantai 9.12. klo 12-14 B123'
  - 'tiistai 10.12. klo 12-14 B123'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
